const express = require('express')
const formidable = require('express-formidable')
const {requireSignin, itemOwner} = require('../middlewares')
const {create, items, image, sellerItems,removeItem, readItem, updateItem, userOrders, searchItems} = require('../controllers/item')

const router = express.Router()
router.post('/create-item',requireSignin,formidable(), create)
router.get('/items', items)
router.get('/item/image/:itemId', image)
router.get('/seller-items', requireSignin, sellerItems)
router.delete('/delete-item/:itemId',requireSignin,itemOwner, removeItem)
router.get('/item/:itemId', readItem)
router.put('/update-item/:itemId', requireSignin, itemOwner, formidable(), updateItem)
router.get('/user-orders', requireSignin, userOrders)
router.post('/search-items', searchItems)
module.exports = router